apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  - eu-central-1a
  - eu-central-1b
  - eu-central-1c
metadata:
  name: demo-eks
  region: eu-central-1
  version: "1.29"
  tags:
    karpenter.sh/discovery: demo-eks
    created-by: eks-workshop-v2
    env: demo-eks
iam:
  withOIDC: true
vpc:
  cidr: 10.1.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
addons:
  - name: vpc-cni
    version: 1.14.1
    configurationValues: '{"env":{"ENABLE_PREFIX_DELEGATION":"true", "ENABLE_POD_ENI":"true", "POD_SECURITY_GROUP_ENFORCING_MODE":"standard"},"enableNetworkPolicy": "true"}'
    resolveConflicts: overwrite
managedNodeGroups:
  - name: demo-eks-ng
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    instanceType: t3a.medium
    privateNetworking: true
    releaseVersion: "1.29.0-20240129"
    updateConfig:
      maxUnavailablePercentage: 50
    labels:
      workshop-default: "yes"
